# Generated by Django 3.0.3 on 2020-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=models.CharField(max_length=254),
        ),
    ]
