# Generated by Django 3.0.3 on 2020-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_status',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
