# Generated by Django 3.0.3 on 2020-03-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_usersubscription_subscription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscription_status',
            new_name='status',
        ),
    ]
