# Generated by Django 3.0.3 on 2020-03-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200315_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
