# Generated by Django 3.0.3 on 2020-03-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=254)),
                ('chart_type', models.CharField(max_length=50)),
                ('display_order', models.IntegerField()),
            ],
        ),
    ]
