# Generated by Django 3.0.3 on 2020-03-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_charttype_subscription_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartType',
        ),
    ]
