# Generated by Django 3.0.3 on 2020-03-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_barchart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchart',
            name='title',
            field=models.CharField(max_length=254),
        ),
    ]
