# Generated by Django 3.0.3 on 2020-03-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_linechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='linechart',
            name='date_format',
            field=models.CharField(default='', max_length=50),
        ),
    ]
